services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4080
    volumes:
      - ./frontend:/app
      - /app/node_modules # Optional: prevents overwriting node_modules in dev
    command: npm run dev

  api:
    build: ./api
    ports:
      - "4080:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
      - /app/node_modules/.prisma # Optional: same as frontend
