services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    command: npm run dev

  api:
    build: ./api
    ports:
      - "4080:3000"
    environment:
      - NODE_ENV=development
