services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://ec2-16-176-203-250.ap-southeast-2.compute.amazonaws.com:4080
    command: npm run dev

  api:
    build: ./api
    ports:
      - "4080:3000"
    environment:
      - NODE_ENV=development
